### ISSUE TITLE
 Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by kun19951117** [opendatalab/MinerU#1435]
### Description of the bug | 错误描述

windows  开启GPU加速后提示
![image](https://github.com/user-attachments/assets/89c06c2c-86d0-4bde-819d-ac8a89c781bd)

### How to reproduce the bug | 如何复现

![image](https://github.com/user-attachments/assets/c8d9b039-8ab6-486b-adfe-eb1695096f9b)

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
windows需要按这个教程安装才能开启cuda加速

https://github.com/opendatalab/MinerU/blob/master/docs/README_Windows_CUDA_Acceleration_zh_CN.md

**Comment by kun19951117** [comment]
你好辛苦了，已经解决了
&nbsp;


辉忆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaomeng ***@***.***&gt;; 
发送时间: 2025年1月7日(星期二) 凌晨0:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [opendatalab/MinerU]  Torch not compiled with CUDA enabled (Issue #1435)














 
windows需要按这个教程安装才能开启cuda加速
 
https://github.com/opendatalab/MinerU/blob/master/docs/README_Windows_CUDA_Acceleration_zh_CN.md
