### ISSUE TITLE
Out of memory error on GPU 0.

### ISSUE THREAD

**Issue by cyKron613** [opendatalab/MinerU#1698]
### Description of the bug | 错误描述

在magic-pdf.json中指定了 cuda在其他卡上。但是会在0卡上创建1.75kb的显存。但是 我们服务器上0卡是爆满的。开辟不了空间。这种情况怎么解决呢？

![Image](https://github.com/user-attachments/assets/f82fc246-bc97-4e41-8623-832cd16abd75)

### How to reproduce the bug | 如何复现

正常magic-pdf 命令跑即可

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

1.0.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
paddle不受device参数控制，只能通过环境变量更改使用的显卡，

例如：

可以在paddle初始化之前通过`os.environ["CUDA_VISIBLE_DEVICES"]=1`设置环境变量到卡1

**Comment by cyKron613** [comment]
解决了谢谢， 还有一个其他问题想问一下。 我在python脚本的循环中遍历执行magic-pdf命令。 会不会有性能的影响。比如会重复初始化模型实例 或者 其他对象的重复实例化。 让速度越来越慢

**Comment by myhloli** [comment]
每次调用magic-pdf都会重新初始化模型，如果是解析本地文档，建议可以通过命令行输入pdf目录的方式，一次性解析多个文档，这样仅需做一次模型初始化动作。另外python脚本可以通过python api调用magic-pdf库实现解析，这样仅需在首次调用时进行一次模型初始化动作。

python api 调用代码可以参考：https://github.com/opendatalab/MinerU/blob/master/demo/demo.py
