### ISSUE TITLE
拉容器跑nvidia-smi, cuda显示是N/A

### ISSUE THREAD

**Issue by yangtianyu92** [opendatalab/MinerU#1744]
### Description of the bug | 错误描述

用的是非常落后的V100
正常容器都是可以看到nvidia-smi cuda 12.0
docker run --rm -it --gpus=all mineru:latest /bin/bash -c "echo 'source /opt/mineru_venv/bin/activate' >> ~/.bashrc && exec bash"
正常输入magic-pdf --help
结果报错ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
用的docker版本能同步一下吗，我觉得可能是我这个docker版本可能比较新？

### How to reproduce the bug | 如何复现

Error: Can not import paddle core while this file exists: /opt/mineru_venv/lib/python3.10/site-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "/opt/mineru_venv/bin/magic-pdf", line 5, in <module>
    from magic_pdf.tools.cli import cli
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/tools/cli.py", line 12, in <module>
    from magic_pdf.tools.common import do_parse, parse_pdf_methods
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/tools/common.py", line 13, in <module>
    from magic_pdf.model.doc_analyze_by_custom_model import doc_analyze
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 5, in <module>
    import paddle
  File "/opt/mineru_venv/lib/python3.10/site-packages/paddle/__init__.py", line 33, in <module>
    from .base import core  # noqa: F401
  File "/opt/mineru_venv/lib/python3.10/site-packages/paddle/base/__init__.py", line 38, in <module>
    from . import (  # noqa: F401
  File "/opt/mineru_venv/lib/python3.10/site-packages/paddle/base/backward.py", line 25, in <module>
    from . import core, framework, log_helper, unique_name
  File "/opt/mineru_venv/lib/python3.10/site-packages/paddle/base/core.py", line 384, in <module>
    raise e
  File "/opt/mineru_venv/lib/python3.10/site-packages/paddle/base/core.py", line 267, in <module>
    from . import libpaddle
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

1.0.x

### Device mode | 设备模式

cuda

**Comment by yangtianyu92** [comment]
我觉得尽量避开paddle这个库，虽然我也很喜欢paddle-ocr这个项目。我生产上的推理环境都是避免使用。
这个库很多设定非常神奇，手机OCR三方库文档错误全靠我常年读心术去读作者咋想的，NER推理也出现过爆显卡事故， export CUDA_VISIBLE_DEVICES=0，1这种对paddle可以不起效用，张量的设定非常神秘 ，各种奇怪的事情都会发生。
虽然不做防呆设计会省很多事，但是额外的要求你去做各种浪费时间的行为，很多时候你也想不通他是怎么想的。

**Comment by myhloli** [comment]
`docker run --rm --gpus=all nvidia/cuda:12.1.0-base-ubuntu22.04 nvidia-smi`
这个测试能正常输出吗？

**Comment by yangtianyu92** [comment]
这个命令可以正常输出，我现在再升级下系统版本和显卡驱动

---- 回复的原邮件 ----
| 发件人 | Xiaomeng ***@***.***> |
| 发送日期 | 2025年02月24日 14:44 |
| 收件人 | opendatalab/MinerU ***@***.***> |
| 抄送人 | yangtianyu92 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [opendatalab/MinerU] 拉容器跑nvidia-smi, cuda显示是N/A (Issue #1744) |

docker run --rm --gpus=all nvidia/cuda:12.1.0-base-ubuntu22.04 nvidia-smi
这个测试能正常输出吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

myhloli left a comment (opendatalab/MinerU#1744)

docker run --rm --gpus=all nvidia/cuda:12.1.0-base-ubuntu22.04 nvidia-smi
这个测试能正常输出吗？

**Comment by Simonqujian78** [comment]
如何解决的，我拉去的docker也是这个问题，我是win11+5090D
