### ISSUE TITLE
Cuda Out of Memory , 当符号很多的时候

### ISSUE THREAD

**Issue by clooney2007** [opendatalab/MinerU#2379]
### 🔎 Search before asking | 提交之前请先搜索

- [x] I have searched the MinerU [Readme](https://github.com/opendatalab/MinerU) and found no similar bug report.
- [x] I have searched the MinerU [Issues](https://github.com/opendatalab/MinerU/issues) and found no similar bug report.
- [x] I have searched the MinerU [Discussions](https://github.com/opendatalab/MinerU/discussions) and found no similar bug report.

### Description of the bug | 错误描述

magic-pdf , cuda 12.8  torch2.7 windows 11专业版

当转换下列书籍的前 100页，报错 cuda out of memory, 公式很多，很复杂

QUANTUM FIELD THEORY 《Feynman Path Integrals andDiagrammatic Techniques in Condensed Matter》
LUKONG CORNELIUS FAIE ，CRC Press

### How to reproduce the bug | 如何复现

<img width="1256" alt="Image" src="https://github.com/user-attachments/assets/7b7040a9-78b0-4a1b-9c1a-780e0f5dd561" />

### Operating System Mode | 操作系统类型

Windows

### Operating System Version| 操作系统版本

win11 专业版

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

1.3.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
windows可以用内存当共享显存用，堆点内存撑一下就好了

**Comment by carcoonzyk** [comment]
> windows可以用内存当共享显存用，堆点内存撑一下就好了

仍然会出问题.
windows驱动程序启动“偏好内存回退”，仍然会爆显存而导致报错，并观察到实际并未使用系统内存：


```sh
注册表修改cuda sysmem fallback policy
```

**Comment by myhloli** [comment]
windows不用任何配置就可以用一半的内存当显存吧，可以在任务管理器里的gpu图表里确认下

**Comment by carcoonzyk** [comment]
> windows不用任何配置就可以用一半的内存当显存吧，可以在任务管理器里的gpu图表里确认下

![Image](https://github.com/user-attachments/assets/6f72c0ec-9323-410c-8fa4-fa5bcc819c5f)

**Comment by myhloli** [comment]
这看着有63g显存，不应该能爆吧，跑下任务监控下呢

**Comment by carcoonzyk** [comment]
> 这看着有63g显存，不应该能爆吧，跑下任务监控下呢

用python脚本手动分割pdf成150页并按批次加载识别才没爆显存。

主要是cuda设备不肯使用系统内存

```sh
╰─ & F:/ProgramData/miniconda3/envs/mineru/python.exe y:/文档/MinerU知识库/WAIT/magic.py                                                                             0:17<00:00,  7.72it/s]
信息论 基础理论与应用 第4版 (傅祖芸) (Z-Library)_13_to_150.pdf                                                                                                       2:10<00:00, 30.91it/s]
2025-04-27 22:01:20.397 | INFO     | magic_pdf.data.dataset:__init__:157 - lang: None                                                                           xt: T0:22<00:00,  6.25it/s]
2025-04-27 22:01:22.040 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:67 - cid_count: 0, text_len: 1501, cid_chars_radio: 0.0                   _te     0:01<00:00,  5.35it/s]
2025-04-27 22:01:22.046 | WARNING  | magic_pdf.filter.pdf_classify_by_type:classify:335 - OCR needed based on classification result, by_image_area: False, by        :49<00:00, 127.34it/s]by_text: True, by_avg_words: True, by_img_num: True, by_img_narrow_strips: True, by_invalid_chars: True                                                         ly_fo0:11<00:00, 11.89it/s]
2025-04-27 22:01:26.206 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:may_batch_image_analyze:275 - gpu_memory: 16 GB, batch_ratio: 16            app
2025-04-27 22:01:26.208 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:68 - DocAnalysis init, this may take some times, layout_model: doclayout_yolo, , apply_formula: True, apply_ocr: True, apply_table: True, table_model: rapid_table, lang: None                                                                 alab\
2025-04-27 22:01:26.208 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:82 - using device: cuda                                                        dat     o
2025-04-27 22:01:26.208 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:86 - using models_dir: C:\Users\Administrator\.cache\modelscope\hub\models\openendatalab\PDF-Extract-Kit-1___0/models
2025-04-27 22:01:31.018 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:164 - DocAnalysis init done!                                                      38 [0
2025-04-27 22:01:31.018 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:custom_model_init:116 - model init cost: 4.811367034912109                  8/1
Layout Predict: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13   38 [0138/138 [00:39<00:00,  3.51it/s]                                                                                                                             8/1
MFD Predict: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13   31 [0138/138 [00:17<00:00,  7.72it/s]                                                                                                                             /40
MFR Predict: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4031   38 [031/4031 [02:10<00:00, 30.91it/s]                                                                                                                             8/1
OCR-det Predict: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13   /7 [0138/138 [00:22<00:00,  6.25it/s]                                                                                                                             | 7
Table Predict: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   7 [00██| 7/7 [00:01<00:00,  5.35it/s]                                                                                                                             632
OCR-rec Predict: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6327/   38 [07/6327 [00:49<00:00, 127.34it/s]                                                                                                                             8/1
Processing pages: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13138/138 [00:11<00:00, 11.89it/s]
2025-04-27 22:06:05.470 | INFO     | magic_pdf.pdf_parse_union_core_v2:pdf_parse_union:1021 - llm aided formula time: 0.0
2025-04-27 22:06:05.470 | INFO     | magic_pdf.pdf_parse_union_core_v2:pdf_parse_union:1028 - llm aided text time: 0.0                                          0\aut
2025-04-27 22:06:18.081 | INFO     | magic_pdf.pdf_parse_union_core_v2:pdf_parse_union:1035 - llm aided title time: 12.61                                    _15
2025-04-27 22:06:28.731 | INFO     | magic_pdf.tools.common:_do_parse:243 - local output dir is output\信息论 基础理论与应用 第4版 (傅祖芸) (Z-Library)_13_toto_150\auto
```

**Comment by carcoonzyk** [comment]
> 这看着有63g显存，不应该能爆吧，跑下任务监控下呢

我发现MFR Predict识别下，16G显存尽量在4500块下，才能保持通过

**Comment by clooney2007** [comment]
> python脚本手动分割pdf成150页并按批次加载识别才没爆显存。
> 
> 主要是cuda设备不肯使用系统内存

我的是使用了系统内存，仍然爆了； 3080ti 64g 内存。

我的和这个兄弟差不多，第一轮的 MFR Predict 最后几个 10%~20%的时候开始卡内存
**_不同的是， 我的底下的windows 的共享显存也耗光了，我的笔记本 3080ti ，就是上面我用的那本书_**；
原书 350页， 拆成 每个 100页之后，后三个可以成功完成，前面两个 100页都是失败

**第一个100页，拆成两个 50页才可以成功。**

感觉就是某些符号密集的页面，触发了类似BUG的东西。

某些300页的书，是可以成功，没有那么多符号的时候。

**Comment by clooney2007** [comment]
> > python脚本手动分割pdf成150页并按批次加载识别才没爆显存。
> > 主要是cuda设备不肯使用系统内存
> 
> 我的是使用了系统内存，仍然爆了； 3080ti 64g 内存。
> 
> 我的和这个兄弟差不多，第一轮的 MFR Predict 最后几个 10%~20%的时候开始卡内存 **_不同的是， 我的底下的windows 的共享显存也耗光了，我的笔记本 3080ti ，就是上面我用的那本书_**； 原书 350页， 拆成 每个 100页之后，后三个可以成功完成，前面两个 100页都是失败
> 
> **第一个100页，拆成两个 50页才可以成功。**
> 
> 感觉就是某些符号密集的页面，触发了类似BUG的东西。
> 
> 某些300页的书，是可以成功，没有那么多符号的时候。

系统共享显存占用曲线 成 45度 向上占用，到 45G 的时候， out of memeory.
