### ISSUE TITLE
昇腾910适配问题：torch和onnx同时初始化acl导致aclError：10002

### ISSUE THREAD

**Issue by S0b3Rr** [opendatalab/MinerU#2547]
### 🔎 Search before asking | 提交之前请先搜索

- [x] I have searched the MinerU [Readme](https://github.com/opendatalab/MinerU) and found no similar bug report.
- [x] I have searched the MinerU [Issues](https://github.com/opendatalab/MinerU/issues) and found no similar bug report.
- [x] I have searched the MinerU [Discussions](https://github.com/opendatalab/MinerU/discussions) and found no similar bug report.

### 基本环境：
- torch_npu==2.3.1
- onnxruntime_cann==1.20.0
### 模型使用：
``` json
"layout-config": {
        "model": "doclayout_yolo"
    },
"formula-config": {
        "mfd_model": "yolo_v8_mfd",
        "mfr_model": "unimernet_small",
        "enable": true
    },
"table-config": {
        "model": "rapid_table",
        "sub_model": "slanet_plus",
        "enable": true,
        "max_time": 400
    }
```

rapid_table使用onnx计算框架，但rapid_table官方原生并不支持onnxruntime_cann。我尝试更改rapid_table使用onnxruntime_cann但出现了torch_npu和onnxruntime_cann同时初始化ACL的错误。（如果有人能跑那说明你的rapid_table被降级到cpu了）

#### 错误信息
``` bash
[E:onnxruntime:Default, provider_bridge_ort.cc:1890 TryGetProviderInfo_CANN] /home/code/onnxruntime/onnxruntime/core/providers/cann/cann_call.cc:143 bool onnxruntime::CannCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = int; bool THRW = true] /home/code/onnxruntime/onnxruntime/core/providers/cann/cann_call.cc:137 bool onnxruntime::CannCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = int; bool THRW = true] CANN failure 100002: ACL_ERROR_REPEAT_INITIALIZE ; NPU=0 ; hostname=dont-mind-my-host ; expr=aclInit(nullptr);
```

## 总的来说，这应该是一个在昇腾架构下多计算框架兼容性的bug（如有误解请不吝指正）

请问能不能在npu运行时添加一个检查ACL初始化的机制，来避免被不同框架重复初始化ACL的机制？

### 部署方式：
裸机部署，但参照贵项目npu部署教程中的Dockerfile来完成

### 其他改动：
修改了rapid_table代码中的onnx EP，增加了CANN EP

----------
完成以上步骤后使用命令行工具即可复现

### Operating System Mode | 操作系统类型

Linux

### Operating System Version| 操作系统版本

Ubuntu 22.04

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

1.3.x

### Device mode | 设备模式

npu

**Comment by myhloli** [comment]
这个简单，不要装onnxnpu，用cpu跑onnx就可以了

**Comment by S0b3Rr** [comment]
> 这个简单，不要装onnxnpu，用cpu跑onnx就可以了

不过这样速度很慢啊，或者说有没有其他的表格模型是用torch跑的能够推荐一下呢？

**Comment by myhloli** [comment]
onnx那个模型很小，不慢的，慢的是ocr，更新到1.3以上就好了

**Comment by S0b3Rr** [comment]
> onnx那个模型很小，不慢的，慢的是ocr，更新到1.3以上就好了

![Image](https://github.com/user-attachments/assets/01d4354b-69b4-40e3-97d1-88bd7640b2ef)
我们的用例可能极端了一些，单pdf中的表格数量较多，但是如图所示图表解析确实慢得有点多，反而是ocr的时间更能够接受一些（这是rapid_table降级到cpu的结果）

**Comment by myhloli** [comment]
建议不要改了，先凑合用

**Comment by S0b3Rr** [comment]
D:
