### ISSUE TITLE
mineru 2.0.3 在910B上执行报错

### ISSUE THREAD

**Issue by delphisharp** [opendatalab/MinerU#2677]
### 🔎 Search before asking | 提交之前请先搜索

- [x] I have searched the MinerU [Readme](https://github.com/opendatalab/MinerU) and found no similar bug report.
- [x] I have searched the MinerU [Issues](https://github.com/opendatalab/MinerU/issues) and found no similar bug report.
- [x] I have searched the MinerU [Discussions](https://github.com/opendatalab/MinerU/discussions) and found no similar bug report.

### Description of the bug | 错误描述

1. 启动基础容器并进入
```
docker run --rm -d --name mineru \
-e ASCEND_VISIBLE_DEVICES=5 \
swr.cn-south-1.myhuaweicloud.com/ascendhub/cann:8.2.rc1.alpha002-910b-ubuntu22.04-py3.10 \
tail -f /dev/null

docker exec -it mineru bash
```

2. 安装 torch 并验证
``` 
pip config set --site global.index-url http://mirrors.aliyun.com/pypi/simple/
pip config set --site global.trusted-host mirrors.aliyun.com
pip install torch==2.7.1 torch_npu==2.7.1rc1 torchvision==0.22.1


import torch
import torch_npu
x = torch.randn(2, 2).npu()
y = torch.randn(2, 2).npu()
z = x.mm(y)
print(z)

```

3. 安装 mineru
```
pip install mineru[pipeline]==2.0.3
pip install numpy==1.24.0 einops
apt install -y curl vim apt libgl1 libglib2.0-0
mineru-models-download -s modelscope -m pipeline

```

4. 执行验证 
```
mineru -p /app/test2.pdf -o  /app/test2 -b pipeline --source local -d npu
```

报错：

```
2025-06-17 03:01:17.848 | ERROR    | mineru.cli.client:parse_doc:189 - call aclnnFlashAttentionScore failed, detail:EZ1001: [PID: 7408] 2025-06-17-03:01:17.844.073 only support kD >= vD, but got kD=24 vD=48
ERR01100 OPS call acl api failed
Traceback (most recent call last):

  File "/usr/local/python3.10.17/bin/mineru", line 8, in <module>
    sys.exit(client.main())
    │   │    │      └ <Command main>
    │   │    └ <module 'mineru.cli.client' from '/usr/local/python3.10.17/lib/python3.10/site-packages/mineru/cli/client.py'>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function Command.main at 0xffff9ce25ab0>
           └ <Command main>
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0xffff9d0facb0>
         │    └ <function Command.invoke at 0xffff9ce25990>
         └ <Command main>
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'input_path': '/app/test2.pdf', 'output_dir': '/app/test2', 'backend': 'pipeline', 'model_source': 'local', 'device_mode': '...
           │   │      │    │           └ <click.core.Context object at 0xffff9d0facb0>
           │   │      │    └ <function main at 0xfffda295bc70>
           │   │      └ <Command main>
           │   └ <function Context.invoke at 0xffff9ce24d30>
           └ <click.core.Context object at 0xffff9d0facb0>
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'input_path': '/app/test2.pdf', 'output_dir': '/app/test2', 'backend': 'pipeline', 'model_source': 'local', 'device_mode': '...
           │         └ ()
           └ <function main at 0xfffda295bc70>
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/mineru/cli/client.py", line 198, in main
    parse_doc([Path(input_path)])
    │          │    └ '/app/test2.pdf'
    │          └ <class 'pathlib.Path'>
    └ <function main.<locals>.parse_doc at 0xfffda295b5b0>
> File "/usr/local/python3.10.17/lib/python3.10/site-packages/mineru/cli/client.py", line 175, in parse_doc
    do_parse(
    └ <function do_parse at 0xfffda295b370>
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/mineru/cli/common.py", line 106, in do_parse
    infer_results, all_image_lists, all_pdf_docs, lang_list, ocr_enabled_list = pipeline_doc_analyze(pdf_bytes_list, p_lang_list, parse_method=parse_method, formula_enable=p_formula_enable,table_enable=p_table_enable)
                                                                                │                    │               │                         │                            │                             └ True
                                                                                │                    │               │                         │                            └ True
                                                                                │                    │               │                         └ 'auto'
                                                                                │                    │               └ ['ch']
                                                                                │                    └ [b'%PDF-1.7\r\n%\xa1\xb3\xc5\xd7\r\n1 0 obj\r\n<</Pages 2 0 R /Type/Catalog>>\r\nendobj\r\n2 0 obj\r\n<</Count 10/Kids[ 4 0 R...
                                                                                └ <function doc_analyze at 0xfffdd9d7ee60>
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/mineru/backend/pipeline/pipeline_analyze.py", line 127, in doc_analyze
    batch_results = batch_image_analyze(batch_image, formula_enable, table_enable)
                    │                   │            │               └ True
                    │                   │            └ True
                    │                   └ [(<PIL.Image.Image image mode=RGB size=1654x2339 at 0xFFFE88CD3E80>, False, 'ch'), (<PIL.Image.Image image mode=RGB size=1654...
                    └ <function batch_image_analyze at 0xfffdd9d7eef0>
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/mineru/backend/pipeline/pipeline_analyze.py", line 193, in batch_image_analyze
    results = batch_model(images_with_extra_info)
              │           └ [(<PIL.Image.Image image mode=RGB size=1654x2339 at 0xFFFE88CD3E80>, False, 'ch'), (<PIL.Image.Image image mode=RGB size=1654...
              └ <mineru.backend.pipeline.batch_analyze.BatchAnalyze object at 0xfffe88cd3c10>
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/mineru/backend/pipeline/batch_analyze.py", line 57, in __call__
    images_formula_list = self.model.mfr_model.batch_predict(
                          │    │     │         └ <function UnimernetModel.batch_predict at 0xfffdade1fa30>
                          │    │     └ <mineru.model.mfr.unimernet.Unimernet.UnimernetModel object at 0xfffe8bce7fd0>
                          │    └ <mineru.backend.pipeline.model_init.MineruPipelineModel object at 0xfffe88bf5570>
                          └ <mineru.backend.pipeline.batch_analyze.BatchAnalyze object at 0xfffe88cd3c10>
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/mineru/model/mfr/unimernet/Unimernet.py", line 118, in batch_predict
    output = self.model.generate({"image": mf_img})
             │    │     │                  └ tensor([[[[-4.5625, -4.5625, -4.5625,  ..., -4.5625, -4.5625, -4.5625],
             │    │     │                              [-4.5625, -4.5625, -4.5625,  ..., -4.5625, ...
             │    │     └ <function UnimernetModel.generate at 0xfffe86377130>
             │    └ UnimernetModel(
             │        (encoder): UnimerSwinModel(
             │          (embeddings): UnimerSwinEmbeddings(
             │            (patch_embeddings): UnimerSwinPat...
             └ <mineru.model.mfr.unimernet.Unimernet.UnimernetModel object at 0xfffe8bce7fd0>
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/mineru/model/mfr/unimernet/unimernet_hf/modeling_unimernet.py", line 482, in generate
    outputs = super().generate(
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {'pixel_values': tensor([[[[-4.5625, -4.5625, -4.5625,  ..., -4.5625, -4.5625, -4.5625],
           │     │                   [-4.5625, -4.5625, -4.5625...
           │     └ (UnimernetModel(
           │         (encoder): UnimerSwinModel(
           │           (embeddings): UnimerSwinEmbeddings(
           │             (patch_embeddings): UnimerSwinPa...
           └ <function GenerationMixin.generate at 0xfffdaa96f490>
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/transformers/generation/utils.py", line 2597, in generate
    result = self._sample(
             │    └ <function GenerationMixin._sample at 0xfffdaa96f880>
             └ UnimernetModel(
                 (encoder): UnimerSwinModel(
                   (embeddings): UnimerSwinEmbeddings(
                     (patch_embeddings): UnimerSwinPat...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/transformers/generation/utils.py", line 3557, in _sample
    outputs = self(**model_inputs, return_dict=True)
              │      └ {'decoder_input_ids': tensor([[0],
              │                [0],
              │                [0],
              │                [0],
              │                [0],
              │                [0],
              │                [0],
              │                [0],...
              └ UnimernetModel(
                  (encoder): UnimerSwinModel(
                    (embeddings): UnimerSwinEmbeddings(
                      (patch_embeddings): UnimerSwinPat...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {'decoder_input_ids': tensor([[0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],...
           │    │           └ ()
           │    └ <function Module._call_impl at 0xfffded879ab0>
           └ UnimernetModel(
               (encoder): UnimerSwinModel(
                 (embeddings): UnimerSwinEmbeddings(
                   (patch_embeddings): UnimerSwinPat...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {'decoder_input_ids': tensor([[0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],...
           │             └ ()
           └ <bound method VisionEncoderDecoderModel.forward of UnimernetModel(
               (encoder): UnimerSwinModel(
                 (embeddings): UnimerSwin...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/transformers/models/vision_encoder_decoder/modeling_vision_encoder_decoder.py", line 553, in forward
    decoder_outputs = self.decoder(
                      └ UnimernetModel(
                          (encoder): UnimerSwinModel(
                            (embeddings): UnimerSwinEmbeddings(
                              (patch_embeddings): UnimerSwinPat...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {'input_ids': tensor([[0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                ...
           │    │           └ ()
           │    └ <function Module._call_impl at 0xfffded879ab0>
           └ UnimerMBartForCausalLM(
               (model): UnimerMBartDecoderWrapper(
                 (decoder): UnimerMBartDecoder(
                   (embed_tokens): Unimer...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {'input_ids': tensor([[0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],
           │             │                ...
           │             └ ()
           └ <bound method UnimerMBartForCausalLM.forward of UnimerMBartForCausalLM(
               (model): UnimerMBartDecoderWrapper(
                 (decoder): ...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/mineru/model/mfr/unimernet/unimernet_hf/unimer_mbart/modeling_unimer_mbart.py", line 2280, in forward
    outputs = self.model.decoder(
              └ UnimerMBartForCausalLM(
                  (model): UnimerMBartDecoderWrapper(
                    (decoder): UnimerMBartDecoder(
                      (embed_tokens): Unimer...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {'input_ids': tensor([[0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                 [0],
           │    │           │                ...
           │    │           └ ()
           │    └ <function Module._call_impl at 0xfffded879ab0>
           └ UnimerMBartDecoder(
               (embed_tokens): UnimerMBartScaledWordEmbedding(50000, 768, padding_idx=1)
               (embed_positions): UnimerMB...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {'input_ids': tensor([[0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],
           │             │                 [0],
           │             │                ...
           │             └ ()
           └ <bound method UnimerMBartDecoder.forward of UnimerMBartDecoder(
               (embed_tokens): UnimerMBartScaledWordEmbedding(50000, 768, ...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/mineru/model/mfr/unimernet/unimernet_hf/unimer_mbart/modeling_unimer_mbart.py", line 1520, in forward
    layer_outputs = decoder_layer(
                    └ UnimerMBartDecoderLayer(
                        (self_attn): UnimerMBartSdpaAttention(
                          (q_proj): Linear(in_features=768, out_features=384, bia...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {'attention_mask': None, 'encoder_hidden_states': tensor([[[-1.3525, -1.2236,  0.3311,  ..., -0.5845,  0.3789,  0.0552],
           │    │           │             ...
           │    │           └ (tensor([[[ 0.1741,  0.2886,  0.3208,  ..., -0.1154,  0.4375,  0.5469]],
           │    │             
           │    │                     [[ 0.1741,  0.2886,  0.3208,  ..., -0.1154,...
           │    └ <function Module._call_impl at 0xfffded879ab0>
           └ UnimerMBartDecoderLayer(
               (self_attn): UnimerMBartSdpaAttention(
                 (q_proj): Linear(in_features=768, out_features=384, bia...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {'attention_mask': None, 'encoder_hidden_states': tensor([[[-1.3525, -1.2236,  0.3311,  ..., -0.5845,  0.3789,  0.0552],
           │             │             ...
           │             └ (tensor([[[ 0.1741,  0.2886,  0.3208,  ..., -0.1154,  0.4375,  0.5469]],
           │               
           │                       [[ 0.1741,  0.2886,  0.3208,  ..., -0.1154,...
           └ <bound method UnimerMBartDecoderLayer.forward of UnimerMBartDecoderLayer(
               (self_attn): UnimerMBartSdpaAttention(
                 (q_pro...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/mineru/model/mfr/unimernet/unimernet_hf/unimer_mbart/modeling_unimer_mbart.py", line 822, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
    │                                                     └ UnimerMBartDecoderLayer(
    │                                                         (self_attn): UnimerMBartSdpaAttention(
    │                                                           (q_proj): Linear(in_features=768, out_features=384, bia...
    └ tensor([[[ 0.1520,  0.2063,  0.1326,  ..., -0.0835,  0.3362,  0.3240]],
      
              [[ 0.1520,  0.2063,  0.1326,  ..., -0.0835, ...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {'hidden_states': tensor([[[ 0.1520,  0.2063,  0.1326,  ..., -0.0835,  0.3362,  0.3240]],
           │    │           │         
           │    │           │                 [[ 0.1520,  0.2063,  0.132...
           │    │           └ ()
           │    └ <function Module._call_impl at 0xfffded879ab0>
           └ UnimerMBartSdpaAttention(
               (q_proj): Linear(in_features=768, out_features=384, bias=True)
               (k_proj): Linear(in_features=768...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {'hidden_states': tensor([[[ 0.1520,  0.2063,  0.1326,  ..., -0.0835,  0.3362,  0.3240]],
           │             │         
           │             │                 [[ 0.1520,  0.2063,  0.132...
           │             └ ()
           └ <bound method UnimerMBartSdpaAttention.forward of UnimerMBartSdpaAttention(
               (q_proj): Linear(in_features=768, out_features=...
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/mineru/model/mfr/unimernet/unimernet_hf/unimer_mbart/modeling_unimer_mbart.py", line 653, in forward
    attn_output = torch.nn.functional.scaled_dot_product_attention(
                  │     │  │          └ <built-in function scaled_dot_product_attention>
                  │     │  └ <module 'torch.nn.functional' from '/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/functional.py'>
                  │     └ <module 'torch.nn' from '/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/__init__.py'>
                  └ <module 'torch' from '/usr/local/python3.10.17/lib/python3.10/site-packages/torch/__init__.py'>

RuntimeError: call aclnnFlashAttentionScore failed, detail:EZ1001: [PID: 7408] 2025-06-17-03:01:17.844.073 only support kD >= vD, but got kD=24 vD=48
ERR01100 OPS call acl api failed
-> Cannot close object, library is destroyed. This may cause a memory leak!
``` 
export USE_FLASH_ATTENTION=0 添加无效
aclnnFlashAttentionScore only support kD >= vD, but got kD=24 vD=48

### How to reproduce the bug | 如何复现

swr.cn-south-1.myhuaweicloud.com/ascendhub/cann:8.2.rc1.alpha002-910b-ubuntu22.04-py3.10 \

### Operating System Mode | 操作系统类型

Linux

### Operating System Version| 操作系统版本

镜像： swr.cn-south-1.myhuaweicloud.com/ascendhub/cann:8.2.rc1.alpha002-910b-ubuntu22.04-py3.10 \

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

1.3.x

### Device mode | 设备模式

npu

**Comment by delphisharp** [comment]
使用其它镜像安装 torch== 2.4.0 也报一样的错误 

换用  pip install transformers==4.49.0  一样报错

**Comment by myhloli** [comment]
看上去好像是npu不支持SdpaAttention导致的

**Comment by myhloli** [comment]
升级下2.0.4试试呢，npu配置时会改成eager模式，可能就能运行了

**Comment by delphisharp** [comment]
谢谢老板。我明天试试。

**Comment by delphisharp** [comment]
问题已解决。谢谢老板，老板威武。

老板哪里有二维码，请喝杯咖啡 ^_^

**Comment by myhloli** [comment]
可以加入我们的微信群，在群里发个红包😊

**Comment by pandaupc** [comment]
大佬如何解决的，方便沟通下吗
