### ISSUE TITLE
在5090上启用 vllm-engine报错 : Engine core initialization failed.

### ISSUE THREAD

**Issue by refrainD** [opendatalab/MinerU#3582]
### 🔎 Search before asking | 提交之前请先搜索

- [x] I have searched the MinerU [Readme](https://github.com/opendatalab/MinerU) and found no similar bug report.
- [x] I have searched the MinerU [Issues](https://github.com/opendatalab/MinerU/issues) and found no similar bug report.
- [x] I have searched the MinerU [Discussions](https://github.com/opendatalab/MinerU/discussions) and found no similar bug report.

### 🤖 Consult the online AI assistant for assistance | 在线 AI 助手咨询

- [x] I have consulted the [online AI assistant](https://deepwiki.com/opendatalab/MinerU) but was unable to obtain a solution to the issue.

## 启动日志
Start init vLLM engine...
Downloading Model from https://www.modelscope.cn to directory: /root/.cache/modelscope/hub/models/OpenDataLab/MinerU2.5-2509-1.2B
2025-09-23 00:43:49,659 - modelscope - INFO - Target directory already exists, skipping creation.
INFO 09-23 00:43:54 [__init__.py:241] Automatically detected platform cuda.
2025-09-23 00:43:55.954 | INFO     | mineru.backend.vlm.custom_logits_processors:enable_custom_logits_processors:40 - compute_capability: 12.0 >= 8.0 and vllm version: 0.10.1.1 >= 0.10.1, enable custom_logits_processors
INFO 09-23 00:44:01 [__init__.py:711] Resolved architecture: Qwen2VLForConditionalGeneration
INFO 09-23 00:44:01 [__init__.py:1750] Using max model len 16384
INFO 09-23 00:44:01 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=5120.
WARNING 09-23 00:44:03 [__init__.py:2921] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 09-23 00:44:07 [__init__.py:241] Automatically detected platform cuda.
(EngineCore_0 pid=185) INFO 09-23 00:44:07 [core.py:636] Waiting for init message from front-end.
(EngineCore_0 pid=185) INFO 09-23 00:44:07 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='/root/.cache/modelscope/hub/models/OpenDataLab/MinerU2___5-2509-1___2B', speculative_config=None, tokenizer='/root/.cache/modelscope/hub/models/OpenDataLab/MinerU2___5-2509-1___2B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=16384, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/root/.cache/modelscope/hub/models/OpenDataLab/MinerU2___5-2509-1___2B, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":1,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":256,"local_cache_dir":null}
(EngineCore_0 pid=185) INFO 09-23 00:44:10 [parallel_state.py:1134] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
(EngineCore_0 pid=185) INFO 09-23 00:44:10 [topk_topp_sampler.py:50] Using FlashInfer for top-p & top-k sampling.
(EngineCore_0 pid=185) INFO 09-23 00:44:12 [gpu_model_runner.py:1953] Starting to load model /root/.cache/modelscope/hub/models/OpenDataLab/MinerU2___5-2509-1___2B...
(EngineCore_0 pid=185) INFO 09-23 00:44:12 [gpu_model_runner.py:1985] Loading model from scratch...
(EngineCore_0 pid=185) WARNING 09-23 00:44:12 [cuda.py:211] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
(EngineCore_0 pid=185) INFO 09-23 00:44:12 [cuda.py:328] Using Flash Attention backend on V1 engine.
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  3.62it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  3.62it/s]
(EngineCore_0 pid=185) 
(EngineCore_0 pid=185) INFO 09-23 00:44:12 [default_loader.py:262] Loading weights took 0.34 seconds
(EngineCore_0 pid=185) INFO 09-23 00:44:13 [gpu_model_runner.py:2007] Model loading took 2.1637 GiB and 0.488382 seconds
(EngineCore_0 pid=185) INFO 09-23 00:44:13 [gpu_model_runner.py:2591] Encoder cache will be initialized with a budget of 14175 tokens, and profiled with 1 video items of the maximum feature size.
CUDA error (/__w/xformers/xformers/third_party/flash-attention/hopper/flash_fwd_launch_template.h:188): invalid argument
2025-09-23 00:44:15.622 | ERROR    | mineru.cli.gradio_app:main:277 - Engine core initialization failed. See root cause above. Failed core proc(s): {}
Traceback (most recent call last):

  File "/usr/local/bin/mineru-gradio", line 7, in <module>
    sys.exit(main())
    │   │    └ <Command main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function Command.main at 0x7e71cc059760>
           └ <Command main>
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7e71cc3a07a0>
         │    └ <function Command.invoke at 0x7e71cc059440>
         └ <Command main>
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'server_name': '0.0.0.0', 'server_port': 7860, 'vllm_engine_enable': True, 'example_enable': True, 'api_enable': True, 'max_...
           │   │      │    │           └ <click.core.Context object at 0x7e71cc3a07a0>
           │   │      │    └ <function main at 0x7e716318fc40>
           │   │      └ <Command main>
           │   └ <function Context.invoke at 0x7e71cc058680>
           └ <click.core.Context object at 0x7e71cc3a07a0>
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'server_name': '0.0.0.0', 'server_port': 7860, 'vllm_engine_enable': True, 'example_enable': True, 'api_enable': True, 'max_...
           │         └ ()
           └ <function main at 0x7e716318fc40>
  File "/usr/local/lib/python3.12/dist-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           │ │                       │       └ {'server_name': '0.0.0.0', 'server_port': 7860, 'vllm_engine_enable': True, 'example_enable': True, 'api_enable': True, 'max_...
           │ │                       └ ()
           │ └ <function get_current_context at 0x7e71cc0031a0>
           └ <function main at 0x7e71631b40e0>
> File "/usr/local/lib/python3.12/dist-packages/mineru/cli/gradio_app.py", line 269, in main
    predictor = model_singleton.get_model(
                │               └ <function ModelSingleton.get_model at 0x7e716318dee0>
                └ <mineru.backend.vlm.vlm_analyze.ModelSingleton object at 0x7e717285f170>
  File "/usr/local/lib/python3.12/dist-packages/mineru/backend/vlm/vlm_analyze.py", line 117, in get_model
    vllm_async_llm = AsyncLLM.from_engine_args(AsyncEngineArgs(**kwargs))
                     │        │                │                 └ {'gpu_memory_utilization': 0.5, 'model': '/root/.cache/modelscope/hub/models/OpenDataLab/MinerU2___5-2509-1___2B', 'logits_pr...
                     │        │                └ <class 'vllm.engine.arg_utils.AsyncEngineArgs'>
                     │        └ <classmethod(<function AsyncLLM.from_engine_args at 0x7e6fd654c680>)>
                     └ <class 'vllm.v1.engine.async_llm.AsyncLLM'>
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 202, in from_engine_args
    return cls(
           └ <class 'vllm.v1.engine.async_llm.AsyncLLM'>
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 120, in __init__
    self.engine_core = EngineCoreClient.make_async_mp_client(
    │                  │                └ <staticmethod(<function EngineCoreClient.make_async_mp_client at 0x7e6fd65702c0>)>
    │                  └ <class 'vllm.v1.engine.core_client.EngineCoreClient'>
    └ <vllm.v1.engine.async_llm.AsyncLLM object at 0x7e6dcef16b10>
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 102, in make_async_mp_client
    return AsyncMPClient(*client_args)
           │              └ (VllmConfig(model_config=ModelConfig(model='/root/.cache/modelscope/hub/models/OpenDataLab/MinerU2___5-2509-1___2B', runner='...
           └ <class 'vllm.v1.engine.core_client.AsyncMPClient'>
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 767, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 446, in __init__
    with launch_core_engines(vllm_config, executor_class,
         │                   │            └ <class 'vllm.v1.executor.abstract.UniProcExecutor'>
         │                   └ VllmConfig(model_config=ModelConfig(model='/root/.cache/modelscope/hub/models/OpenDataLab/MinerU2___5-2509-1___2B', runner='a...
         └ <function launch_core_engines at 0x7e6fd657db20>
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
         │    └ <generator object launch_core_engines at 0x7e6dcc041b60>
         └ <contextlib._GeneratorContextManager object at 0x7e6dca58fd40>
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/utils.py", line 706, in launch_core_engines
    wait_for_engine_startup(
    └ <function wait_for_engine_startup at 0x7e6fd657dc60>
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/utils.py", line 759, in wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "

RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}

## 环境
Docker镜像: vllm/vllm-openai:v0.10.1.1
 显卡: NVIDIA GeForce RTX 5090
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.65.06              Driver Version: 580.65.06      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+

### How to reproduce the bug | 如何复现

NVIDIA GeForce RTX 5090 使用镜像vllm/vllm-openai:v0.10.1.1构建容器gradio时报错，pipeline，transformer都能正常使用，但是vllm不行。

### Operating System Mode | 操作系统类型

Linux

### Operating System Version| 操作系统版本

Ubuntu

### Python version | Python 版本

3.12

### Software version | 软件版本 (mineru --version)

2.0.x

### Device mode | 设备模式

cuda

**Comment by refrainD** [comment]
root@fe4927ac0771:/vllm-workspace# mineru -v
mineru, version 2.5.3

当前的mineru版本为2.5.3，镜像使用vllm0.10.1.1，请问当前是否支持50系显卡使用？

**Comment by wwb91** [comment]
请问解决了没有？

**Comment by refrainD** [comment]
还没有，用以前sglang的版本吧

**Comment by LittleRoommmm** [comment]
> root@fe4927ac0771:/vllm-workspace# mineru -v mineru, version 2.5.3
> 
> 当前的mineru版本为2.5.3，镜像使用vllm0.10.1.1，请问当前是否支持50系显卡使用？

挂vllm-openai:v0.11可以正常运行

**Comment by refrainD** [comment]
> > root@fe4927ac0771:/vllm-workspace# mineru -v mineru, version 2.5.3
> > 当前的mineru版本为2.5.3，镜像使用vllm0.10.1.1，请问当前是否支持50系显卡使用？
> 
> 挂vllm-openai:v0.11可以正常运行

使用vllm-openai:v0.11.0仍和原来一样的报错，是否还需要额外修改？

**Comment by mengdeer589** [comment]
vllm单独部署就行，vllm用最新的，mineru通过http方式调用

**Comment by refrainD** [comment]
@mengdeer589 感谢！  新版本2.6.2按照文档部署已经能正常使用了

**Comment by zwclh** [comment]
> [@mengdeer589](https://github.com/mengdeer589) 感谢！ 新版本2.6.2按照文档部署已经能正常使用了

怎么部署？

**Comment by refrainD** [comment]
@zwclh 按照官方的docker部署文档就可以。[Dockfile](https://github.com/opendatalab/MinerU/blob/master/docker/global/Dockerfile)

**Comment by enjoyour** [comment]
您好,同样的环境,mineru, version 2.6.6,还是报错:
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:38000 (Press CTRL+C to quit)
Start MinerU FastAPI Service: http://0.0.0.0:38000
API documentation: http://0.0.0.0:38000/docs
INFO:     10.1.1.82:59666 - "GET /docs HTTP/1.1" 200 OK
INFO:     10.1.1.82:59666 - "GET /docs HTTP/1.1" 200 OK
INFO:     10.1.1.82:59666 - "GET /openapi.json HTTP/1.1" 200 OK
2025-12-09 04:02:08.081 | WARNING  | mineru.utils.pdf_page_id:get_end_page_id:8 - end_page_id is out of range, use images length
INFO 12-09 04:02:15 [__init__.py:241] Automatically detected platform cuda.
2025-12-09 04:02:21.114 | INFO     | mineru.backend.vlm.utils:enable_custom_logits_processors:46 - compute_capability: 12.0 >= 8.0 and vllm version: 0.10.1.1 >= 0.10.1, enable custom_logits_processors
INFO 12-09 04:02:26 [__init__.py:711] Resolved architecture: Qwen2VLForConditionalGeneration
INFO 12-09 04:02:26 [__init__.py:1750] Using max model len 16384
INFO 12-09 04:02:26 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=5120.
WARNING 12-09 04:02:27 [__init__.py:2921] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 12-09 04:02:30 [__init__.py:241] Automatically detected platform cuda.
(EngineCore_0 pid=44) INFO 12-09 04:02:31 [core.py:636] Waiting for init message from front-end.
(EngineCore_0 pid=44) INFO 12-09 04:02:31 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='/root/.cache/modelscope/hub/models/OpenDataLab/MinerU2___5-2509-1___2B', speculative_config=None, tokenizer='/root/.cache/modelscope/hub/models/OpenDataLab/MinerU2___5-2509-1___2B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=16384, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/root/.cache/modelscope/hub/models/OpenDataLab/MinerU2___5-2509-1___2B, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":1,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":256,"local_cache_dir":null}
(EngineCore_0 pid=44) INFO 12-09 04:02:33 [parallel_state.py:1134] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
(EngineCore_0 pid=44) INFO 12-09 04:02:33 [topk_topp_sampler.py:50] Using FlashInfer for top-p & top-k sampling.
(EngineCore_0 pid=44) INFO 12-09 04:02:35 [gpu_model_runner.py:1953] Starting to load model /root/.cache/modelscope/hub/models/OpenDataLab/MinerU2___5-2509-1___2B...
(EngineCore_0 pid=44) INFO 12-09 04:02:35 [gpu_model_runner.py:1985] Loading model from scratch...
(EngineCore_0 pid=44) WARNING 12-09 04:02:35 [cuda.py:211] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
(EngineCore_0 pid=44) INFO 12-09 04:02:35 [cuda.py:328] Using Flash Attention backend on V1 engine.
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  2.98it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  2.98it/s]
(EngineCore_0 pid=44) 
(EngineCore_0 pid=44) INFO 12-09 04:02:36 [default_loader.py:262] Loading weights took 0.37 seconds
(EngineCore_0 pid=44) INFO 12-09 04:02:36 [gpu_model_runner.py:2007] Model loading took 2.1637 GiB and 0.496979 seconds
(EngineCore_0 pid=44) INFO 12-09 04:02:36 [gpu_model_runner.py:2591] Encoder cache will be initialized with a budget of 14175 tokens, and profiled with 1 video items of the maximum feature size.
CUDA error (/__w/xformers/xformers/third_party/flash-attention/hopper/flash_fwd_launch_template.h:188): invalid argument
2025-12-09 04:02:38.373 | ERROR    | mineru.cli.fast_api:parse_pdf:306 - Engine core initialization failed. See root cause above. Failed core proc(s): {}
Traceback (most recent call last):

  File "/usr/local/bin/mineru-api", line 7, in <module>
    sys.exit(main())
    │   │    └ <Command main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function Command.main at 0x710f16553920>
           └ <Command main>
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x710f170d0710>
         │    └ <function Command.invoke at 0x710f16553600>
         └ <Command main>
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'host': '0.0.0.0', 'port': 38000, 'reload': False}
           │   │      │    │           └ <click.core.Context object at 0x710f170d0710>
           │   │      │    └ <function main at 0x710e76a5ce00>
           │   │      └ <Command main>
           │   └ <function Context.invoke at 0x710f16552840>
           └ <click.core.Context object at 0x710f170d0710>
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'host': '0.0.0.0', 'port': 38000, 'reload': False}
           │         └ ()
           └ <function main at 0x710e76a5ce00>
  File "/usr/local/lib/python3.12/dist-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           │ │                       │       └ {'host': '0.0.0.0', 'port': 38000, 'reload': False}
           │ │                       └ ()
           │ └ <function get_current_context at 0x710f16531300>
           └ <function main at 0x710e76a5cfe0>
  File "/usr/local/lib/python3.12/dist-packages/mineru/cli/fast_api.py", line 336, in main
    uvicorn.run(
    │       └ <function run at 0x710f165a6d40>
    └ <module 'uvicorn' from '/usr/local/lib/python3.12/dist-packages/uvicorn/__init__.py'>
  File "/usr/local/lib/python3.12/dist-packages/uvicorn/main.py", line 580, in run
    server.run()
    │      └ <function Server.run at 0x710f1639a8e0>
    └ <uvicorn.server.Server object at 0x710e76abc9b0>
  File "/usr/local/lib/python3.12/dist-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x710f1639a980>
           │       │   └ <uvicorn.server.Server object at 0x710e76abc9b0>
           │       └ <function run at 0x710f166f16c0>
           └ <module 'asyncio' from '/usr/lib/python3.12/asyncio/__init__.py'>
  File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           │      │   └ <coroutine object Server.serve at 0x710e769404a0>
           │      └ <function Runner.run at 0x710f16762b60>
           └ <asyncio.runners.Runner object at 0x710e76bfb9e0>
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Server.serve() running at /usr/local/lib/python3.12/dist-packages/uvicorn/server.py:71> wai...
           │    │     └ <cyfunction Loop.run_until_complete at 0x710e769213c0>
           │    └ <uvloop.Loop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x710e76bfb9e0>
  File "/usr/local/lib/python3.12/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x710e76b9d580>
  File "/usr/local/lib/python3.12/dist-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769754...
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 38000), '...
                 │    └ <fastapi.applications.FastAPI object at 0x710e76ce5790>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x710e76b9d580>
  File "/usr/local/lib/python3.12/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769754...
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 38000), '...
  File "/usr/local/lib/python3.12/dist-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769754...
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 38000), '...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x710e76961820>
          └ <fastapi.applications.FastAPI object at 0x710e76ce5790>
  File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x710e762cef20>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 38000), '...
          │    └ <starlette.middleware.gzip.GZipMiddleware object at 0x710e76c0fa10>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x710e76961820>
  File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/gzip.py", line 29, in __call__
INFO:     10.1.1.82:59667 - "POST /file_parse HTTP/1.1" 500 Internal Server Error
    await responder(scope, receive, send)
          │         │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x710e762cef20>
          │         │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769...
          │         └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 38000), '...
          └ <starlette.middleware.gzip.GZipResponder object at 0x710e76976180>
  File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/gzip.py", line 130, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x710e762cef20>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 38000), '...
  File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/gzip.py", line 46, in __call__
    await self.app(scope, receive, self.send_with_compression)
          │    │   │      │        │    └ <function IdentityResponder.send_with_compression at 0x710f1540c9a0>
          │    │   │      │        └ <starlette.middleware.gzip.GZipResponder object at 0x710e76976180>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 38000), '...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x710e7700c4a0>
          └ <starlette.middleware.gzip.GZipResponder object at 0x710e76976180>
  File "/usr/local/lib/python3.12/dist-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <bound method IdentityResponder.send_with_compression of <starlette.middleware.gzip.GZipResponder object at 0x710e76976180>>
          │                            │    │    │     │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769...
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 38000), '...
          │                            │    │    └ <starlette.requests.Request object at 0x710e76ad3080>
          │                            │    └ <fastapi.routing.APIRouter object at 0x710e76abc410>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x710e7700c4a0>
          └ <function wrap_app_handling_exceptions at 0x710f1557b1a0>
  File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x710e762cf060>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 38000), '...
          └ <fastapi.routing.APIRouter object at 0x710e76abc410>
  File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x710e762cf060>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 38000), '...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x710e76abc410>>
          └ <fastapi.routing.APIRouter object at 0x710e76abc410>
  File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x710e762cf060>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 38000), '...
          │     └ <function Route.handle at 0x710f155c4680>
          └ APIRoute(path='/file_parse', name='parse_pdf', methods=['POST'])
  File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x710e762cf060>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 38000), '...
          │    └ <function request_response.<locals>.app at 0x710e76a5cb80>
          └ APIRoute(path='/file_parse', name='parse_pdf', methods=['POST'])
  File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x710e762cf060>
          │                            │    │        │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769...
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 38000), '...
          │                            │    └ <starlette.requests.Request object at 0x710e76975370>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x710e762cf100>
          └ <function wrap_app_handling_exceptions at 0x710f1557b1a0>
  File "/usr/local/lib/python3.12/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x710e762cf240>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x710e769...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 38000), '...
          └ <function request_response.<locals>.app.<locals>.app at 0x710e762cf100>
  File "/usr/local/lib/python3.12/dist-packages/starlette/routing.py", line 75, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x710e76975370>
                     └ <function get_request_handler.<locals>.app at 0x710e76a5cd60>
  File "/usr/local/lib/python3.12/dist-packages/fastapi/routing.py", line 302, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x710f1557ad40>
  File "/usr/local/lib/python3.12/dist-packages/fastapi/routing.py", line 213, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'files': [UploadFile(filename='体检中心入职体检报告范本-精选.pdf.pdf', size=40676, headers=Headers({'content-disposition': 'form-data; nam...
                 │         └ <function parse_pdf at 0x710e76a5c900>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[ModelField(field_info=File(Pydant...
> File "/usr/local/lib/python3.12/dist-packages/mineru/cli/fast_api.py", line 194, in parse_pdf
    await aio_do_parse(
          └ <function aio_do_parse at 0x710e76a67d80>
  File "/usr/local/lib/python3.12/dist-packages/mineru/cli/common.py", line 393, in aio_do_parse
    await _async_process_vlm(
          └ <function _async_process_vlm at 0x710e76a67b00>
  File "/usr/local/lib/python3.12/dist-packages/mineru/cli/common.py", line 245, in _async_process_vlm
    middle_json, infer_result = await aio_vlm_doc_analyze(
                                      └ <function aio_doc_analyze at 0x710e76a677e0>
  File "/usr/local/lib/python3.12/dist-packages/mineru/backend/vlm/vlm_analyze.py", line 230, in aio_doc_analyze
    predictor = ModelSingleton().get_model(backend, model_path, server_url, **kwargs)
                │                          │        │           │             └ {}
                │                          │        │           └ None
                │                          │        └ None
                │                          └ 'vllm-async-engine'
                └ <class 'mineru.backend.vlm.vlm_analyze.ModelSingleton'>
  File "/usr/local/lib/python3.12/dist-packages/mineru/backend/vlm/vlm_analyze.py", line 125, in get_model
    vllm_async_llm = AsyncLLM.from_engine_args(AsyncEngineArgs(**kwargs))
                     │        │                │                 └ {'gpu_memory_utilization': 0.5, 'model': '/root/.cache/modelscope/hub/models/OpenDataLab/MinerU2___5-2509-1___2B', 'logits_pr...
                     │        │                └ <class 'vllm.engine.arg_utils.AsyncEngineArgs'>
                     │        └ <classmethod(<function AsyncLLM.from_engine_args at 0x710e766744a0>)>
                     └ <class 'vllm.v1.engine.async_llm.AsyncLLM'>
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 202, in from_engine_args
    return cls(
           └ <class 'vllm.v1.engine.async_llm.AsyncLLM'>
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 120, in __init__
    self.engine_core = EngineCoreClient.make_async_mp_client(
    │                  │                └ <staticmethod(<function EngineCoreClient.make_async_mp_client at 0x710e76610180>)>
    │                  └ <class 'vllm.v1.engine.core_client.EngineCoreClient'>
    └ <vllm.v1.engine.async_llm.AsyncLLM object at 0x710b1e1672c0>
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 102, in make_async_mp_client
    return AsyncMPClient(*client_args)
           │              └ (VllmConfig(model_config=ModelConfig(model='/root/.cache/modelscope/hub/models/OpenDataLab/MinerU2___5-2509-1___2B', runner='...
           └ <class 'vllm.v1.engine.core_client.AsyncMPClient'>
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 767, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 446, in __init__
    with launch_core_engines(vllm_config, executor_class,
         │                   │            └ <class 'vllm.v1.executor.abstract.UniProcExecutor'>
         │                   └ VllmConfig(model_config=ModelConfig(model='/root/.cache/modelscope/hub/models/OpenDataLab/MinerU2___5-2509-1___2B', runner='a...
         └ <function launch_core_engines at 0x710e76609b20>
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
         │    └ <generator object launch_core_engines at 0x710b1afd3a60>
         └ <contextlib._GeneratorContextManager object at 0x710b1ae31940>
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/utils.py", line 706, in launch_core_engines
    wait_for_engine_startup(
    └ <function wait_for_engine_startup at 0x710e76609bc0>
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/utils.py", line 759, in wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "

RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}

**Comment by refrainD** [comment]
> vllm单独部署就行，vllm用最新的，mineru通过http方式调用

@enjoyour 目前我使用vllmv0.11.0镜像按照官网的部署文档成功部署了mineru-v2.6.6版本的，你可以参考这篇[文章](https://blog.csdn.net/m0_57697768/article/details/154112663?spm=1011.2415.3001.5331)，按照官网的dockerfile内容部署就行。

<img width="1313" height="790" alt="Image" src="https://github.com/user-attachments/assets/d48ea27e-4865-4f79-baaa-6600666f6643" />

**Comment by enjoyour** [comment]
@refrainD  好的, 5090服务器构建mineru镜像,一定要vllm-openai:0.11.0
