### ISSUE TITLE
使用VLLM运行模型报错

### ISSUE THREAD

**Issue by xiaoyuer2019** [opendatalab/MinerU#3677]
### 🔎 Search before asking | 提交之前请先搜索

- [x] I have searched the MinerU [Readme](https://github.com/opendatalab/MinerU) and found no similar bug report.
- [x] I have searched the MinerU [Issues](https://github.com/opendatalab/MinerU/issues) and found no similar bug report.
- [x] I have searched the MinerU [Discussions](https://github.com/opendatalab/MinerU/discussions) and found no similar bug report.

### 🤖 Consult the online AI assistant for assistance | 在线 AI 助手咨询

- [x] I have consulted the [online AI assistant](https://deepwiki.com/opendatalab/MinerU) but was unable to obtain a solution to the issue.

### Description of the bug | 错误描述

(EngineCore_DP0 pid=948) ERROR 10-09 07:56:07 [core.py:720] torch.AcceleratorError: CUDA error: an illegal memory access was encountered
(EngineCore_DP0 pid=948) ERROR 10-09 07:56:07 [core.py:720] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(EngineCore_DP0 pid=948) ERROR 10-09 07:56:07 [core.py:720] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(EngineCore_DP0 pid=948) ERROR 10-09 07:56:07 [core.py:720] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

报了个an illegal memory access was encountered 是什么原因造成的呢？

vllm 2080ti 22g

### How to reproduce the bug | 如何复现

使用命令行推理不报错，但是vllm就会报错

### Operating System Version| 操作系统版本

python3.11

### Python version | Python 版本

3.11

### Software version | 软件版本 (mineru --version)

2.0.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
在T4（turing）设备上无法复现该问题，在colab的t4显卡上可正常使用vllm加速vlm模式，相关log可参考：https://colab.research.google.com/gist/myhloli/a3cb16570ab3cfeadf9d8f0ac91b4fca/mineru_demo.ipynb#scrollTo=t53WETM90pKr

建议将显卡驱动升级到最新，并创建一个新的虚拟环境安装测试。

**Comment by ChrisKimZHT** [comment]
我的场景下，升级到 vLLM 0.12.0 问题解决：`pip install vllm==0.12.0`
