### ISSUE TITLE
好像不支持 torch==2.8.0+cu129

### ISSUE THREAD

**Issue by tiptinker** [opendatalab/MinerU#3853]
### 🔎 Search before asking | 提交之前请先搜索

- [x] I have searched the MinerU [Readme](https://github.com/opendatalab/MinerU) and found no similar bug report.
- [x] I have searched the MinerU [Issues](https://github.com/opendatalab/MinerU/issues) and found no similar bug report.
- [x] I have searched the MinerU [Discussions](https://github.com/opendatalab/MinerU/discussions) and found no similar bug report.

### 🤖 Consult the online AI assistant for assistance | 在线 AI 助手咨询

- [x] I have consulted the [online AI assistant](https://deepwiki.com/opendatalab/MinerU) but was unable to obtain a solution to the issue.

### Description of the bug | 错误描述

torch                              2.8.0+cu129
torchaudio                         2.8.0+cu129
torchvision                        0.23.0+cu129

Build cuda_12.9.r12.9/compiler.35813241_0

```
INFO 10-28 13:08:56 [__init__.py:216] Automatically detected platform cuda.
2025-10-28 13:08:59.629 | INFO     | mineru.backend.vlm.utils:enable_custom_logits_processors:43 - compute_capability: 8.9 >= 8.0 and vllm version: 0.11.0 >= 0.10.1, enable custom_logits_processors
Fetching 14 files: 100%|█████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 24264.57it/s]
start vllm server: ['/home/cheng/vllm/venv/bin/mineru-vllm-server', 'serve', '/home/cheng/.cache/huggingface/hub/models--opendatalab--MinerU2.5-2509-1.2B/snapshots/879e58bdd9566632b27a8a81f0e2961873311f67', '--port', '30000', '--enforce-eager', '--gpu-memory-utilization', '0.5', '--max-model-len', '4096', '--disable-log-requests', '--disable-log-stats', '--no-enable-prefix-caching', '--logits-processors', 'mineru_vl_utils:MinerULogitsProcessor']
WARNING 10-28 13:09:01 [__init__.py:1742] argument '--disable-log-requests' is deprecated and replaced with '--enable-log-requests'. This will be removed in v0.12.0.
(APIServer pid=5714) INFO 10-28 13:09:01 [api_server.py:1839] vLLM API server version 0.11.0
(APIServer pid=5714) INFO 10-28 13:09:01 [utils.py:233] non-default args: {'model_tag': '/home/cheng/.cache/huggingface/hub/models--opendatalab--MinerU2.5-2509-1.2B/snapshots/879e58bdd9566632b27a8a81f0e2961873311f67', 'port': 30000, 'model': '/home/cheng/.cache/huggingface/hub/models--opendatalab--MinerU2.5-2509-1.2B/snapshots/879e58bdd9566632b27a8a81f0e2961873311f67', 'max_model_len': 4096, 'enforce_eager': True, 'logits_processors': ['mineru_vl_utils:MinerULogitsProcessor'], 'gpu_memory_utilization': 0.5, 'enable_prefix_caching': False, 'disable_log_stats': True}
(APIServer pid=5714) INFO 10-28 13:09:01 [model.py:547] Resolved architecture: Qwen2VLForConditionalGeneration
(APIServer pid=5714) `torch_dtype` is deprecated! Use `dtype` instead!
(APIServer pid=5714) INFO 10-28 13:09:01 [model.py:1510] Using max model len 4096
(APIServer pid=5714) INFO 10-28 13:09:01 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=2048.
(APIServer pid=5714) INFO 10-28 13:09:01 [__init__.py:381] Cudagraph is disabled under eager mode
INFO 10-28 13:09:03 [__init__.py:216] Automatically detected platform cuda.
(EngineCore_DP0 pid=5765) INFO 10-28 13:09:05 [core.py:644] Waiting for init message from front-end.
(EngineCore_DP0 pid=5765) INFO 10-28 13:09:05 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='/home/cheng/.cache/huggingface/hub/models--opendatalab--MinerU2.5-2509-1.2B/snapshots/879e58bdd9566632b27a8a81f0e2961873311f67', speculative_config=None, tokenizer='/home/cheng/.cache/huggingface/hub/models--opendatalab--MinerU2.5-2509-1.2B/snapshots/879e58bdd9566632b27a8a81f0e2961873311f67', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/home/cheng/.cache/huggingface/hub/models--opendatalab--MinerU2.5-2509-1.2B/snapshots/879e58bdd9566632b27a8a81f0e2961873311f67, enable_prefix_caching=False, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
(EngineCore_DP0 pid=5765) WARNING 10-28 13:09:06 [interface.py:381] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708] EngineCore failed to start.
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708] Traceback (most recent call last):
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 699, in run_engine_core
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 498, in __init__
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]     super().__init__(vllm_config, executor_class, log_stats,
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 83, in __init__
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]     self.model_executor = executor_class(vllm_config)
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]     self._init_executor()
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 54, in _init_executor
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]     self.collective_rpc("init_device")
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]     return [run_method(self.driver_worker, method, args, kwargs)]
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3122, in run_method
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]     return func(*args, **kwargs)
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 259, in init_device
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]     self.worker.init_device()  # type: ignore
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]     ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 161, in init_device
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]     current_platform.set_device(self.device)
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/platforms/cuda.py", line 83, in set_device
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]     _ = torch.zeros(1, device=device)
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708] torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(EngineCore_DP0 pid=5765) ERROR 10-28 13:09:06 [core.py:708]
(EngineCore_DP0 pid=5765) Process EngineCore_DP0:
(EngineCore_DP0 pid=5765) Traceback (most recent call last):
(EngineCore_DP0 pid=5765)   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=5765)     self.run()
(EngineCore_DP0 pid=5765)   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=5765)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=5765)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 712, in run_engine_core
(EngineCore_DP0 pid=5765)     raise e
(EngineCore_DP0 pid=5765)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 699, in run_engine_core
(EngineCore_DP0 pid=5765)     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=5765)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=5765)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 498, in __init__
(EngineCore_DP0 pid=5765)     super().__init__(vllm_config, executor_class, log_stats,
(EngineCore_DP0 pid=5765)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 83, in __init__
(EngineCore_DP0 pid=5765)     self.model_executor = executor_class(vllm_config)
(EngineCore_DP0 pid=5765)                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=5765)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
(EngineCore_DP0 pid=5765)     self._init_executor()
(EngineCore_DP0 pid=5765)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 54, in _init_executor
(EngineCore_DP0 pid=5765)     self.collective_rpc("init_device")
(EngineCore_DP0 pid=5765)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
(EngineCore_DP0 pid=5765)     return [run_method(self.driver_worker, method, args, kwargs)]
(EngineCore_DP0 pid=5765)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=5765)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3122, in run_method
(EngineCore_DP0 pid=5765)     return func(*args, **kwargs)
(EngineCore_DP0 pid=5765)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=5765)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 259, in init_device
(EngineCore_DP0 pid=5765)     self.worker.init_device()  # type: ignore
(EngineCore_DP0 pid=5765)     ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=5765)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 161, in init_device
(EngineCore_DP0 pid=5765)     current_platform.set_device(self.device)
(EngineCore_DP0 pid=5765)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/platforms/cuda.py", line 83, in set_device
(EngineCore_DP0 pid=5765)     _ = torch.zeros(1, device=device)
(EngineCore_DP0 pid=5765)         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=5765) torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
(EngineCore_DP0 pid=5765) CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(EngineCore_DP0 pid=5765) For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(EngineCore_DP0 pid=5765) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(EngineCore_DP0 pid=5765)
(APIServer pid=5714) Traceback (most recent call last):
(APIServer pid=5714)   File "/home/cheng/vllm/venv/bin/mineru-vllm-server", line 7, in <module>
(APIServer pid=5714)     sys.exit(main())
(APIServer pid=5714)              ^^^^^^
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/mineru/model/vlm_vllm_model/server.py", line 61, in main
(APIServer pid=5714)     vllm_main()
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/entrypoints/cli/main.py", line 54, in main
(APIServer pid=5714)     args.dispatch_function(args)
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/entrypoints/cli/serve.py", line 57, in cmd
(APIServer pid=5714)     uvloop.run(run_server(args))
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/uvloop/__init__.py", line 96, in run
(APIServer pid=5714)     return __asyncio.run(
(APIServer pid=5714)            ^^^^^^^^^^^^^^
(APIServer pid=5714)   File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
(APIServer pid=5714)     return runner.run(main)
(APIServer pid=5714)            ^^^^^^^^^^^^^^^^
(APIServer pid=5714)   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
(APIServer pid=5714)     return self._loop.run_until_complete(task)
(APIServer pid=5714)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=5714)   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/uvloop/__init__.py", line 48, in wrapper
(APIServer pid=5714)     return await main
(APIServer pid=5714)            ^^^^^^^^^^
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1884, in run_server
(APIServer pid=5714)     await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1902, in run_server_worker
(APIServer pid=5714)     async with build_async_engine_client(
(APIServer pid=5714)   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
(APIServer pid=5714)     return await anext(self.gen)
(APIServer pid=5714)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 180, in build_async_engine_client
(APIServer pid=5714)     async with build_async_engine_client_from_engine_args(
(APIServer pid=5714)   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
(APIServer pid=5714)     return await anext(self.gen)
(APIServer pid=5714)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 225, in build_async_engine_client_from_engine_args
(APIServer pid=5714)     async_llm = AsyncLLM.from_vllm_config(
(APIServer pid=5714)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/utils/__init__.py", line 1572, in inner
(APIServer pid=5714)     return fn(*args, **kwargs)
(APIServer pid=5714)            ^^^^^^^^^^^^^^^^^^^
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 207, in from_vllm_config
(APIServer pid=5714)     return cls(
(APIServer pid=5714)            ^^^^
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 134, in __init__
(APIServer pid=5714)     self.engine_core = EngineCoreClient.make_async_mp_client(
(APIServer pid=5714)                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 102, in make_async_mp_client
(APIServer pid=5714)     return AsyncMPClient(*client_args)
(APIServer pid=5714)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 769, in __init__
(APIServer pid=5714)     super().__init__(
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 448, in __init__
(APIServer pid=5714)     with launch_core_engines(vllm_config, executor_class,
(APIServer pid=5714)   File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
(APIServer pid=5714)     next(self.gen)
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/engine/utils.py", line 732, in launch_core_engines
(APIServer pid=5714)     wait_for_engine_startup(
(APIServer pid=5714)   File "/home/cheng/vllm/venv/lib/python3.12/site-packages/vllm/v1/engine/utils.py", line 785, in wait_for_engine_startup
(APIServer pid=5714)     raise RuntimeError("Engine core initialization failed. "
(APIServer pid=5714) RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
```

### How to reproduce the bug | 如何复现

哪里可以看到requirements 呢

### Operating System Mode | 操作系统类型

Linux

### Operating System Version| 操作系统版本

Ubuntu 24.04.1

### Python version | Python 版本

3.12

### Software version | 软件版本 (mineru --version)

>=2.5

### Backend name | 解析后端

vlm

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
建议先参考vllm官方文档 https://docs.vllm.ai/en/latest/getting_started/quickstart.html 把vllm环境装好，我们对环境并没有特殊要求，只要您能正常启动vllm并运行任意模型，都可以正常运行本项目。
